/*

 DICESPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 63

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : Yes.
  Index offset         : 0
  Index counter        : None.

 This file was generated by GBTD v2.2

*/

#ifndef __DiceSprites_h_INCLUDE
#define __DiceSprites_h_INCLUDE

/* Bank of tiles. */
#define DiceSpriteBank 0

/* Super Gameboy palette 0 */
#define DiceSpriteSGBPal0c0 6076
#define DiceSpriteSGBPal0c1 8935
#define DiceSpriteSGBPal0c2 6596
#define DiceSpriteSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define DiceSpriteSGBPal1c0 6076
#define DiceSpriteSGBPal1c1 8935
#define DiceSpriteSGBPal1c2 6596
#define DiceSpriteSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define DiceSpriteSGBPal2c0 6076
#define DiceSpriteSGBPal2c1 8935
#define DiceSpriteSGBPal2c2 6596
#define DiceSpriteSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define DiceSpriteSGBPal3c0 6076
#define DiceSpriteSGBPal3c1 8935
#define DiceSpriteSGBPal3c2 6596
#define DiceSpriteSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define DiceSpriteCGBPal0c0 6076
#define DiceSpriteCGBPal0c1 8935
#define DiceSpriteCGBPal0c2 6596
#define DiceSpriteCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define DiceSpriteCGBPal1c0 6076
#define DiceSpriteCGBPal1c1 8935
#define DiceSpriteCGBPal1c2 6596
#define DiceSpriteCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define DiceSpriteCGBPal2c0 6076
#define DiceSpriteCGBPal2c1 8935
#define DiceSpriteCGBPal2c2 6596
#define DiceSpriteCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define DiceSpriteCGBPal3c0 6076
#define DiceSpriteCGBPal3c1 8935
#define DiceSpriteCGBPal3c2 6596
#define DiceSpriteCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define DiceSpriteCGBPal4c0 6076
#define DiceSpriteCGBPal4c1 8935
#define DiceSpriteCGBPal4c2 6596
#define DiceSpriteCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define DiceSpriteCGBPal5c0 6076
#define DiceSpriteCGBPal5c1 8935
#define DiceSpriteCGBPal5c2 6596
#define DiceSpriteCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define DiceSpriteCGBPal6c0 6076
#define DiceSpriteCGBPal6c1 8935
#define DiceSpriteCGBPal6c2 6596
#define DiceSpriteCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define DiceSpriteCGBPal7c0 6076
#define DiceSpriteCGBPal7c1 8935
#define DiceSpriteCGBPal7c2 6596
#define DiceSpriteCGBPal7c3 5344
/* Metatile index */
extern const unsigned char DiceSpriteIndex[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK0[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK1[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK2[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK3[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK4[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK5[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK6[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK7[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK8[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK9[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK10[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK11[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK12[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK13[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK14[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK15[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK16[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK17[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK18[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK19[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK20[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK21[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK22[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK23[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK24[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK25[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK26[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK27[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK28[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK29[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK30[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK31[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK32[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK33[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK34[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK35[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK36[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK37[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK38[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK39[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK40[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK41[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK42[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK43[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK44[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK45[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK46[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK47[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK48[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK49[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK50[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK51[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK52[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK53[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK54[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK55[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK56[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK57[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK58[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK59[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK60[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK61[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK62[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK63[];
/* Start of tile array. */
extern const unsigned char DiceSpriteBLK64[];

#endif

/* End of DICESPRITES.H */
