/*

 TESTMENU.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 67

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __TestMenu_h_INCLUDE
#define __TestMenu_h_INCLUDE

/* Bank of tiles. */
#define TestTilesBank 0

/* Super Gameboy palette 0 */
#define TestTilesSGBPal0c0 6076
#define TestTilesSGBPal0c1 8935
#define TestTilesSGBPal0c2 6596
#define TestTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define TestTilesSGBPal1c0 6076
#define TestTilesSGBPal1c1 8935
#define TestTilesSGBPal1c2 6596
#define TestTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define TestTilesSGBPal2c0 6076
#define TestTilesSGBPal2c1 8935
#define TestTilesSGBPal2c2 6596
#define TestTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define TestTilesSGBPal3c0 6076
#define TestTilesSGBPal3c1 8935
#define TestTilesSGBPal3c2 6596
#define TestTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define TestTilesCGBPal0c0 6076
#define TestTilesCGBPal0c1 8935
#define TestTilesCGBPal0c2 6596
#define TestTilesCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define TestTilesCGBPal1c0 6076
#define TestTilesCGBPal1c1 8935
#define TestTilesCGBPal1c2 6596
#define TestTilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define TestTilesCGBPal2c0 6076
#define TestTilesCGBPal2c1 8935
#define TestTilesCGBPal2c2 6596
#define TestTilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define TestTilesCGBPal3c0 6076
#define TestTilesCGBPal3c1 8935
#define TestTilesCGBPal3c2 6596
#define TestTilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define TestTilesCGBPal4c0 6076
#define TestTilesCGBPal4c1 8935
#define TestTilesCGBPal4c2 6596
#define TestTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define TestTilesCGBPal5c0 6076
#define TestTilesCGBPal5c1 8935
#define TestTilesCGBPal5c2 6596
#define TestTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define TestTilesCGBPal6c0 6076
#define TestTilesCGBPal6c1 8935
#define TestTilesCGBPal6c2 6596
#define TestTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define TestTilesCGBPal7c0 6076
#define TestTilesCGBPal7c1 8935
#define TestTilesCGBPal7c2 6596
#define TestTilesCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char TestTiles[];

#endif

/* End of TESTMENU.H */
